apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 80
      targetPort: 8000   # <-- Use the port your container is exposing
      nodePort: 30001    # <-- This is the port you'll access in browser
